version: "3"

services: 
  frontend:
    image: knotnuttanai/soft-arch:frontend
    container_name: frontend
    expose: 
      - 5000

  backend:
    image: knotnuttanai/soft-arch:backend
    container_name: backend
    expose: 
      - 9000

  nginx:
    image: knotnuttanai/soft-arch:nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443